spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: dmall-third-party
server:
  port: 30000
alibaba:
  cloud:
    access-key: LTAI4G1R4HTorWjiz48qg9Ko
    secret-key: wslKxmQgCr0mEZknHxV3H08eP1vbLy
    oss:
      endpoint: oss-cn-shenzhen.aliyuncs.com

