spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: dmall-third-party
server:
  port: 30000
alibaba:
  cloud:
    access-key: LTAI4GB37S6BZEyVd5pHUoW7
    secret-key: jgF4tLoSmdgaNDcZaCpWWQVP0O4Bdk
    oss:
      endpoint: oss-cn-shenzhen.aliyuncs.com

